export { default as audi_e_tron_9_black } from './audi-e-tron-9-black.png'
export { default as battery_insight_1 } from './battery-insight-1.svg'
export { default as battery_insight_2 } from './battery-insight-2.svg'
export { default as battery_insight_3 } from './battery-insight-3.svg'
export { default as momentum_e_1 } from './momentum-e-platform-1.svg' 
export { default as momentum_e_2 } from './momentum-e-platform-2.svg' 
export { default as momentum_e_3 } from './momentum-e-platform-3.svg' 
export { default as dashboard_need_help } from './dashboard-need-help.png'
// export { default as background_1} from './background-connecting-lines-dots-structure.jpg'
// export { default as background_2} from './background-connecting-lines-dots.jpg'
// export { default as background-3} from './background-flowing-connecting-lines.jpg'
// export { default as background-4} from './banned-with-halftone-dots-design.jpg'
// export {default as unrivaled_performance_img1} from './collage-customer-experience-concept-1.png'
// export {default as unrivaled_performance_img2} from './growth-concept.png'