export { default as HomePage } from './HomePage';
export { default as Heading } from './heading';
export { default as ItemCard } from './ItemCard';
export { default as GetInTouch } from './getInTouch'
export { default as PricingCard } from './Pricing/PricingCard';
export { default as CompanyStats } from './CompanyStats'
export { default as BoxContainer } from './BoxContainer'
export { default as AboutProduct } from './AboutProduct';
export { default as Reveal } from './Reveal';